---
- name: Create base application directory
  file:
    path: "{{ app_root }}"
    state: directory
    mode: 0777
  tags: adddir

- name: Create log file
  file:
    path: "/var/log/{{ app_service_name }}.log"
    state: touch
    mode: u=rwx,g=r,o=rwx
  tags: addlog

- name: Download nvm installer
  get_url: url="https://raw.githubusercontent.com/creationix/nvm/v{{ nvm_version }}/install.sh" dest=~/nvm-installer.sh mode=u=rwx,g=r,o=x
  tags: install-nvm

- name: Execute the nvm-installer.sh
  command: ~/nvm-installer.sh
  args:
    creates: ~/.nvm/nvm.sh
  tags: install-nvm

- name: Own the nvm script
  file:
    path: ~/.nvm/nvm.sh
    state: touch
    mode: u=rwx,g=r,o=rwx
  tags: install-nvm

- name: Activate nvm
  command: /bin/bash ~/.nvm/nvm.sh
  args:
    chdir: "~/"
  tags: install-nvm

- name: Install node
  shell: |
    source ~/.bashrc
    nvm install "{{ node_version }}"
    nvm use --delete-prefix "v{{ node_version }}" --silent
  tags: install-node
