---
- name: start nodeapp
  shell: |
    source ~/.bashrc
    cd {{ app_root }};
    npm start &>> /var/log/{{ app_service_name }}.log &
    sleep 1
  ignore_errors: yes

- name: stop nodeapp
  shell: "kill $(ps aux | grep 'node' | awk '{print $2}') &>>/dev/null;"
  ignore_errors: yes
